stages:
  - check
  - test

check:
  stage: check
  script:
    - cat app/.env
    - make check

test:
  stage: test
  script:
    - make test

before_script:
  - echo DATABASE_URL=pgsql://rigpickuser:anyPassword@postgres/rigpickdb >> app/.env
  - make

after_script:
  - docker-compose down
  - sudo chmod 777 -R *
