version: '3'

services:
  nginx:
    image: nginx:1.10
    volumes:
      - "./app/:/var/www/html"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker/nginx/symfony.conf:/etc/nginx/symfony.conf"
      - "./docker/nginx/static.conf:/etc/nginx/static.conf"
      - "./docker/nginx/sites-enabled:/etc/nginx/sites-enabled"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
    ports:
      - "${HTTP_PORT}:80"
    links:
      - php-fpm
    networks:
      default:
        aliases:
          - "rigpick.local"

  php-fpm:
    build: ./docker/php-fpm
    command: /bin/bash -c 'php-fpm'
    volumes:
        - "./app:/var/www/html"
        - "./docker/data/php-fpm/root/.composer/auth.json:/root/.composer/auth.json"
    links:
      - postgres
    image: registry.gitlab.com/rigpick/website/php-fpm

  postgres:
    image: postgres:9.6
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "./docker/data/postgres/pgdata:/var/lib/postgresql/data/pgdata"
      - "./docker/data/postgres/dumps:/var/lib/postgresql/dumps"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata

  yarn:
    image: kkarczmarczyk/node-yarn:8.0
    volumes:
        - "./app:/var/www/html"
    working_dir: '/var/www/html'
