sonata_admin:
    title: 'RigPick Panel'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

    security:
            handler: sonata.admin.security.handler.role
            role_admin: ROLE_ADMIN
            role_super_admin: ROLE_ADMIN

    options:
        title_mode: single_text

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
